### ISSUE TITLE
TypeError Cannot read property 'logo' of null

### ISSUE THREAD

**Issue by mcnaveen** [JacobSNGoodwin/nuxt-ghost-starter#14]
Appears under `components/Navigation.vue:19:`

**Comment by JacobSNGoodwin** [comment]
@the-mcnaveen,

Thanks for reporting. I'm looking at it. Let me know if you find anything first, and feel free to submit a PR!

**Comment by JacobSNGoodwin** [comment]
@the-mcnaveen, we had a user report similar behavior in #12 .

Are you running the npm run generate command to get this error?

If so this error should be thrown by ./store.index.js inside of the nuxtServerInit() function. The error should be thrown if one of your api calls fails inside of the try{} block of nuxtServerInit. 

So perhaps something is wrong with your API configuration.

I assume you created a __.env file__ with the your Ghost api key and URI? This is the URI and key you get by creating an Integration called API in your admin panel. But this would definitely make nuxtServerInit fail.

Anyhow, I may be off base, but I just want to cover the basics.

**Comment by mcnaveen** [comment]
I fixed it buddy :smile: 

Here is the `.env` template

> GHOST_URI=http://SITE_URL
> GHOST_KEY=59442ae645d040a3490f0065a5
> SITE_URL=http://SITE_URL

And I faced one more error. So fixed it and made PR #16

**Comment by JacobSNGoodwin** [comment]
@the-mcnaveen,

Glad that fixed the problem.

I appreciate your commit to number #16. I need to make sure that we're automatically applying linting for a consistent style and rule set (we have a nuxt rule set already) upon commits.
