### ISSUE TITLE
Package express question. 

### ISSUE THREAD

**Issue by eclectic-coding** [JacobSNGoodwin/nuxt-ghost-starter#32]
Started experimenting with your starter. Great work.

My question is it seems you have `express` in package.json but it doesn't appeared to be used. Are we using a backend at all? If not we could probably safely remove. If this is the cases, `nodemon` could be removed as well.

I would be glad to make a PR if this is correct.

**Comment by JacobSNGoodwin** [comment]
Thanks,

Maybe I left these in from earlier experimentation, but honestly can't
recall why I included them and I can't see why they'd be necessary.

Go ahead and update the package.json,  make sure everything works after
installing, and if you submit a PR I'll verify it tomorrow!

Thanks!

**Comment by JacobSNGoodwin** [comment]
Closed by #33
